export default [
    {
        id              : 239201565,
        name            : "deepface",
        full_name       : "serengil/deepface",
        html_url        : "https://github.com/serengil/deepface",
        stargazers_count: 1082,
        language        : "Python",
        created_at      : "2020-02-08T20:42:28Z",
        topics          : [
            "face-recognition",
            "vgg-face",
            "facenet",
            "openface",
            "facial-expression-recognition",
            "age-prediction",
            "gender-prediction",
            "race-classification",
            "emotion-recognition",
            "deep-learning",
            "machine-learning",
            "deepface",
            "face-analysis",
            "tensorflow",
            "keras",
            "python",
            "deepid",
            "dlib",
            "arcface",
        ],
    },
    {
        id              : 110724756,
        name            : "colabtools",
        full_name       : "googlecolab/colabtools",
        html_url        : "https://github.com/googlecolab/colabtools",
        stargazers_count: 1113,
        language        : "Python",
        created_at      : "2017-11-14T17:49:51Z",
        topics          : [],
    },
    {
        id              : 202990524,
        name            : "UnityFx.Outline",
        full_name       : "Arvtesh/UnityFx.Outline",
        html_url        : "https://github.com/Arvtesh/UnityFx.Outline",
        stargazers_count: 325,
        language        : "C#",
        created_at      : "2019-08-18T10:43:45Z",
        topics          : [
            "unityfx",
            "outline",
            "image-effects",
            "post-effect",
            "unity",
            "unity3d",
        ],
    },
    {
        "id"              : 9330072,
        "name"            : "Craft",
        "full_name"       : "fogleman/Craft",
        "html_url"        : "https://github.com/fogleman/Craft",
        "stargazers_count": 8471,
        "language"        : "C",
        "created_at"      : "2013-04-09T19:47:38Z",
        "topics"          : null
      },
      {
        "id"              : 143175496,
        "name"            : "baritone",
        "full_name"       : "cabaletta/baritone",
        "html_url"        : "https://github.com/cabaletta/baritone",
        "stargazers_count": 2736,
        "language"        : "Java",
        "created_at"      : "2018-08-01T15:34:21Z",
        "topics"          : null
      },
      {
        "id"              : 19704737,
        "name"            : "langdetect",
        "full_name"       : "Mimino666/langdetect",
        "html_url"        : "https://github.com/Mimino666/langdetect",
        "stargazers_count": 1017,
        "language"        : "Python",
        "created_at"      : "2014-05-12T15:44:46Z",
        "topics"          : null
      },
      {
        "id"              : 3666605,
        "name"            : "List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words",
        "full_name"       : "LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words",
        "html_url"        : "https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words",
        "stargazers_count": 1299,
        "language"        : null,
        "created_at"      : "2012-03-09T02:15:36Z",
        "topics"          : null
      },
];
