export default [
    {
        id: 239201565,
        name: "deepface",
        full_name: "serengil/deepface",
        html_url: "https://github.com/serengil/deepface",
        stargazers_count: 1082,
        language: "Python",
        created_at: "2020-02-08T20:42:28Z",
        topics: [
            "face-recognition",
            "vgg-face",
            "facenet",
            "openface",
            "facial-expression-recognition",
            "age-prediction",
            "gender-prediction",
            "race-classification",
            "emotion-recognition",
            "deep-learning",
            "machine-learning",
            "deepface",
            "face-analysis",
            "tensorflow",
            "keras",
            "python",
            "deepid",
            "dlib",
            "arcface",
        ],
    },
    {
        id: 110724756,
        name: "colabtools",
        full_name: "googlecolab/colabtools",
        html_url: "https://github.com/googlecolab/colabtools",
        stargazers_count: 1113,
        language: "Python",
        created_at: "2017-11-14T17:49:51Z",
        topics: [],
    },
    {
        id: 202990524,
        name: "UnityFx.Outline",
        full_name: "Arvtesh/UnityFx.Outline",
        html_url: "https://github.com/Arvtesh/UnityFx.Outline",
        stargazers_count: 325,
        language: "C#",
        created_at: "2019-08-18T10:43:45Z",
        topics: [
            "unityfx",
            "outline",
            "image-effects",
            "post-effect",
            "unity",
            "unity3d",
        ],
    },
];
